### PR TITLE
Add support for circuit conditions

### PR DESCRIPTION
**Pull request by Genhis**
Limitations:
- Unknown behavior if two stations have the same name and one of them is used to check circuit conditions

I have also made some modifications to `item_count` and `fluid_count` - it shouldn't break anything ~~but I haven't tested those conditions~~. I have tested them both and they work as expected.

If I should change the version number or something else, let me know.

### CODE REVIEW

**Comment by Patapum** [comment]
Thank you for your contribution!

I suppose I will make small amends and include it into next update.

- Optional turning on in map mod settings https://wiki.factorio.com/Tutorial:Mod_settings
- Remove unknown behavior using train.station after the train chose next stop
- Circuit network should sum signals from network to be consistent with how it works elsewhere. Or  
 https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.get_merged_signals

Please let me know if you would like to implement some by yourself

**Comment by Genhis** [comment]
I will change it to use `get_merged_signals()` and will leave mod settings to you.

I would use `train.station` but the problem is that, according to the API documentation, it points to the station where the train is stopped at, not the next station object.

> The train stop this train is stopped at or nil.

Do you have other suggestions how to remove "unknown behavior"? I could iterate through all stations and the one matching the conditions would be selected as the next.

**Comment by Patapum** [comment]
I mixed up train.station with train.path_end_stop 😊

**Comment by Genhis** [comment]
What if I had two stations with the same name and one satisfied the circuit condition?

To be consistent with the disabled stations behavior, I would say that the train should go to the second station and consider the first one as "disabled". However, the train could pathfind to the first station and if we used `train.path_end_stop`, both stations would be skipped because the first one satisfied the condition.

What do you think?

**Comment by Patapum** [comment]
There are no easy way for mod to force train to specific station. Also it looks like idea for more complicated mod - select next station based on conditions. 😊
One more limitation is that content of train and train ID is not available for station circuit.

I prefer to keep it simple leaving other options to heavy mods like LTN, TSM, TrainsCaller

BTW could you please share your ideas on how you using this mod? Maybe on mod discussion page

**Comment by alextd** [comment]
The other problem would be if the circuit is designed to use the train's contents, it won't be available. HM.

**Comment by Genhis** [comment]
That is a good point @alextd. I guess there is nothing we can do in that case.

Anyway, I will push changes requested by @Patapum tomorrow.

**Comment by Genhis** [comment]
@Patapum I've been having some issues with `get_merged_signals()` and `train.path_end_stop` - it doesn't seem to work the way I thought it would. Please make the changes yourself if you want.

**Comment by StopGamer** [comment]
> BTW could you please share your ideas on how you using this mod?

I use it to skip stations when using cargo trains with different items.
Example (bob angel)
I have Engine station that requires Pipes, Gears and Steel.
I use train as input warehouse (cargo slots reserved for all 3) and production feed directly from train.
Also I have 3 supply stations per each resource.

I want to minimize train traffic, so desired behavior is such
 - dispatch train if one resource is absent
 - skip stations corresponding to resources that are present above threshold (1000)
 - fill as full as possible cargo when arrived to supply station 

So I created such conditions
1. Engine station 
     Gear = 0 OR Pipes = 0 OR Steel = 0
2. Supply station
     Corresponding item > 1000  AND T = 19

Where is T is circuit condition generated by timer that activates when train is present and have loop 20 sec (from 0 to 19). When train leaves station it leaves signal as 19 (condition fulfilled)

- If train has more than 1000 supply item station is skipped. T-condition and Item count - both fulfilled
- If train has less than 1000 supply - one condition not fulfilled so train arrives. Moment train arrives timer starts and changes from 19 to 0. So now both conditions unfulfilled. After some time train got fully filled. But it will wait a bit more till timer gets to 19 and leaves.

This should satisfy all required behavior. But fails because circuit condition doesnt supported

Tried to upload some images to illustrate https://imgur.com/gallery/H18s9Si

**Review by Patapum — APPROVED** [review]

**Pull request merged**
